### ISSUE TITLE
NPE in SplunkRumBuilder.build 

### ISSUE THREAD

**Issue by ber4444** [signalfx/splunk-otel-android#1030]
OS version: android14
Model:Galaxy S23
SDK version:1.6.0
Stacktrace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
       at okhttp3.internal.idn.IdnaMappingTable.findRangesOffset(IdnaMappingTable.java:242)
       at okhttp3.internal.idn.IdnaMappingTable.map(IdnaMappingTable.java:130)
       at okhttp3.internal._HostnamesCommonKt.idnToAscii(-HostnamesCommon.kt:322)
       at okhttp3.internal._HostnamesCommonKt.toCanonicalHost(-HostnamesCommon.kt:307)
       at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.java:1448)
       at okhttp3.HttpUrl$Companion.get(HttpUrl.java:1744)
       at okhttp3.HttpUrl$Companion.parse(HttpUrl.java:1754)
       at okhttp3.HttpUrl.parse(HttpUrl.java:34)
       at zipkin2.reporter.okhttp3.InternalOkHttpSender.newEndpoint(InternalOkHttpSender.java:61)
       at zipkin2.reporter.okhttp3.InternalOkHttpSender.newEndpoint(InternalOkHttpSender.java:36)
       at zipkin2.reporter.BaseHttpSender.nextEndpoint(BaseHttpSender.java:108)
       at zipkin2.reporter.BaseHttpSender.<init>(BaseHttpSender.java:96)
       at zipkin2.reporter.BaseHttpSender.<init>(BaseHttpSender.java:78)
       at zipkin2.reporter.okhttp3.InternalOkHttpSender.<init>(InternalOkHttpSender.java:44)
       at zipkin2.reporter.okhttp3.OkHttpSender.<init>(OkHttpSender.java:184)
       at zipkin2.reporter.okhttp3.OkHttpSender$Builder.build(OkHttpSender.java:175)
       at com.splunk.rum.RumInitializer.buildCustomizedZipkinSender(RumInitializer.java:383)
       at com.splunk.rum.RumInitializer.buildStorageBufferingExporter(RumInitializer.java:360)
       at com.splunk.rum.RumInitializer.buildExporter(RumInitializer.java:350)
       at com.splunk.rum.RumInitializer.buildFilteringExporter(RumInitializer.java:328)
       at com.splunk.rum.RumInitializer.lambda$initialize$0(RumInitializer.java:119)
       at io.opentelemetry.android.OpenTelemetryRumBuilder.buildTracerProvider(OpenTelemetryRumBuilder.java:481)
       at io.opentelemetry.android.OpenTelemetryRumBuilder.build(OpenTelemetryRumBuilder.java:320)
       at com.splunk.rum.RumInitializer.initialize(RumInitializer.java:206)
       at com.splunk.rum.SplunkRum.initialize(SplunkRum.java:108)
       at com.splunk.rum.SplunkRumBuilder.build(SplunkRumBuilder.java:348)
```

**Comment by breedx-splk** [comment]
Thanks @ber4444 . Was this a one-off problem or is it easily reproducible? Can you share the code that initializes your `SplunkRum` instance?

**Comment by ber4444** [comment]
Seems to be one-off (so far!), code is:
```
SplunkRum.builder()
        .setRealm("us0")
        .setRumAccessToken(token)
        .setApplicationName("xxx")
        .enableDiskBuffering()
        .setDeploymentEnvironment(BuildConfig.FLAVOR)
        .setGlobalAttributes(
            Attributes.builder()
                .put(StandardAttributes.APP_VERSION, appVersion)
                .put(StandardAttributes.APP_BUILD_TYPE, BuildConfig.BUILD_TYPE)
                .build()
        )
        .build(context)
```

**Comment by breedx-splk** [comment]
That is super weird. So it's down in the url parsing code of okhttp. Because you're passing the `realm` as `us0` it should be pretty straightforward for the sdk to build a parseable url. A couple follow-up questions:

* What version of the splunk rum sdk are you using?
* Are you bringing in a version of okhttp? If so, what version?
* Is the `token` value dynamic or read from somewhere? 

It's making me wonder if the realm or token values might have hidden unicode in them or are somehow broken....but if that were the case, it should be repeatable. Hrmph.

**Comment by ber4444** [comment]
splunk-otel-android:1.6.0
okhttp = '5.0.0-alpha.14'
token is a stable, non-null value, run `ggrep -ohP '[^\x00-\x7F]' CLASS_FILE | sort -u` but didn't find non-ASCII stuff

**Comment by breedx-splk** [comment]
Bleeding edge okhttp. Hmmm. I think maybe we should wait until 5.x is stable before digging too deeply on this.

**Comment by yschimke** [comment]
okhttp 5 is stable for production use, just not API stable. We will hopefully have a stable final release this year.

But there is something strange going on with this, ranges is set to a constant String in okhttp3.internal.idn.IDNA_MAPPING_TABLE. It can't be null.

Bug in OkHttp tracking this https://github.com/square/okhttp/issues/8574#issuecomment-2474763716
