### ISSUE TITLE
Splunk rum crashes protected app

### ISSUE THREAD

**Issue by gjmarkov** [signalfx/splunk-otel-android#313]
Initializing Splunk Rum on app start with a protected version crashes the app.
The crash happens when calling the method `SplunkRum.initialize(Config)`.

Stacktrace:
 ```
java.lang.ExceptionInInitializerError
        at io.opentelemetry.sdk.trace.internal.JcTools.newFixedSizeQueue(Unknown Source:0)
        at io.reactivex.rxjava3.core.Single.<init>(Unknown Source:14)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(Unknown Source:12)
        at com.splunk.rum.RumInitializer.timingClock(Unknown Source:5)
        at com.splunk.rum.RumInitializer.initialize(Unknown Source:93)
        at app.package.android.App.onCreate(Unknown Source:300)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

**Comment by mateuszrzeszutek** [comment]
Hey @gjmarkov , 
I'm not sure what `a protected version` means - can you elaborate?
What version of splunk-otel-android are you using? Can you post your initialization/config code here?

**Comment by gjmarkov** [comment]
Hey @mateuszrzeszutek 
By a protected version, I mean a release version with `proguard` enabled, and also a protected sdk obfuscating the code and other security measurements.

We are using version 0.12.0:` implementation ("com.splunk:splunk-otel-android:0.12.0")`

And here is the initialization/config code:
**Init**
```
	fun init(
		application: Application,
		endpoint: String,
		token: String,
		applicationName: String,
		crashFields: Map<String, String>
	) {
		SplunkRum.initialize(configuration(endpoint, token, applicationName, crashFields), application)
	}
```

**Config**
```
	private fun configuration(
		endpoint: String,
		token: String,
		applicationName: String,
		crashFields: Map<String, String>
	): Config = Config
		.builder()
		.apply {
			beaconEndpoint(endpoint)
			rumAccessToken(token)
			crashReportingEnabled(true)
			debugEnabled(BuildConfig.DEBUG)
			globalAttributes(attributes(crashFields))
			applicationName(applicationName)
		}.build()
```

**Comment by mateuszrzeszutek** [comment]
Is that `java.lang.ExceptionInInitializerError` the full stack trace? Do you perhaps have the cause of the initializer error?

**Comment by gjmarkov** [comment]
This is the full stack trace:
```
java.lang.ExceptionInInitializerError
        at io.opentelemetry.sdk.trace.internal.JcTools.newFixedSizeQueue(Unknown Source:0)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(Unknown Source:14)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(Unknown Source:12)
        at com.splunk.rum.RumInitializer.buildTracerProvider(Unknown Source:5)
        at com.splunk.rum.RumInitializer.initialize(Unknown Source:93)
        at com.splunk.rum.SplunkRum.initialize(Unknown Source:25)
        at com.splunk.rum.SplunkRum.initialize(Unknown Source:5)
        at app.package.android.App.onCreate(Unknown Source:300)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
        at android.app.ActivityThread.access$1700(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: No field producerIndex in class io.opentelemetry.internal.shaded.jctools.queues.MpscArrayQueueProducerIndexField; (declaration of io.opentelemetry.internal.shaded.jctools.queues.MpscArrayQueueProducerIndexField.lvProducerIndex appears in /data/app/~~OPt5T3b5dYHO5w2ajgwpMQ==/app.package.android-DtRSC6tM5VA2HLhfR0d2qQ==/base.apk!classes5.dex)
        at io.opentelemetry.internal.shaded.jctools.util.UnsafeAccess.fieldOffset(Unknown Source:14)
        at io.opentelemetry.internal.shaded.jctools.queues.MpscArrayQueueProducerIndexField.<clinit>(Unknown Source:4)
        at io.opentelemetry.sdk.trace.internal.JcTools.newFixedSizeQueue(Unknown Source:0) 
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(Unknown Source:14) 
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(Unknown Source:12) 
        at com.splunk.rum.RumInitializer.buildTracerProvider(Unknown Source:5) 
        at com.splunk.rum.RumInitializer.initialize(Unknown Source:93) 
        at com.splunk.rum.SplunkRum.initialize(Unknown Source:25) 
        at com.splunk.rum.SplunkRum.initialize(Unknown Source:5) 
        at app.package.android.App.onCreate(Unknown Source:300) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506) 
        at android.app.ActivityThread.access$1700(ActivityThread.java:310) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
     Caused by: java.lang.NoSuchFieldException: No field producerIndex in class io.opentelemetry.internal.shaded.jctools.queues.MpscArrayQueueProducerIndexField; (declaration of io.opentelemetry.internal.shaded.jctools.queues.MpscArrayQueueProducerIndexField.lvProducerIndex appears in /data/app/~~OPt5T3b5dYHO5w2ajgwpMQ==/app.package.android-DtRSC6tM5VA2HLhfR0d2qQ==/base.apk!classes5.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at io.opentelemetry.internal.shaded.jctools.util.UnsafeAccess.fieldOffset(Unknown Source:2)
        at io.opentelemetry.internal.shaded.jctools.queues.MpscArrayQueueProducerIndexField.<clinit>(Unknown Source:4) 
        at io.opentelemetry.sdk.trace.internal.JcTools.newFixedSizeQueue(Unknown Source:0) 
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(Unknown Source:14) 
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(Unknown Source:12) 
        at com.splunk.rum.RumInitializer.buildTracerProvider(Unknown Source:5) 
        at com.splunk.rum.RumInitializer.initialize(Unknown Source:93) 
        at com.splunk.rum.SplunkRum.initialize(Unknown Source:25) 
        at com.splunk.rum.SplunkRum.initialize(Unknown Source:5) 
        at app.package.android.App.onCreate(Unknown Source:300) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506) 
        at android.app.ActivityThread.access$1700(ActivityThread.java:310) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
It maybe looking a bit weird with the packages and the classes' names because it had to be deobfuscated.

**Comment by mateuszrzeszutek** [comment]
I suspect that proguard might be removing some parts from the OpenTelemetry SDK that are actually used; can you configure it so that it keeps all the OpenTelemetry classes/methods/fields? E.g. https://github.com/signalfx/splunk-otel-android/blob/main/splunk-otel-android/consumer-rules.pro#L2
