### ISSUE TITLE
ANR from initializing Splunk

### ISSUE THREAD

**Issue by ber4444** [signalfx/splunk-otel-android#882]
This is reported on prod from lower end devices such as by Motorola.

Stack trace:
```
          main (runnable):tid=1 systid=22938 
       at android.net.NetworkCapabilities.clearAll(NetworkCapabilities.java:357)
       at android.net.NetworkCapabilities.<init>(NetworkCapabilities.java:326)
       at android.net.NetworkCapabilities$1.createFromParcel(NetworkCapabilities.java:2389)
       at android.net.NetworkCapabilities$1.createFromParcel(NetworkCapabilities.java:2386)
       at android.net.NetworkRequest$1.createFromParcel(NetworkRequest.java:662)
       at android.net.NetworkRequest$1.createFromParcel(NetworkRequest.java:660)
       at android.os.Parcel.readTypedObject(Parcel.java:3947)
       at android.net.IConnectivityManager$Stub$Proxy.requestNetwork(IConnectivityManager.java:2472)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4425)
       at android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4966)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4933)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4907)
       at io.opentelemetry.android.instrumentation.network.CurrentNetworkProvider.registerNetworkCallbacks(CurrentNetworkProvider.java:80)
       at io.opentelemetry.android.instrumentation.network.CurrentNetworkProvider.startMonitoring(CurrentNetworkProvider.java:66)
       at io.opentelemetry.android.instrumentation.network.CurrentNetworkProvider.createAndStart(CurrentNetworkProvider.java:44)
       at com.splunk.rum.RumInitializer.initialize(RumInitializer.java:106)
       at com.splunk.rum.SplunkRum.initialize(SplunkRum.java:103)
       at com.splunk.rum.SplunkRumBuilder.build(SplunkRumBuilder.java:333)
```
We are using v1.4 but in your changelog there is no mention of things that would address this in later releases either.

**Comment by ber4444** [comment]
I believe parts of your initializer should go to a thread that is different from the main thread.

**Comment by breedx-splk** [comment]
Hey @ber4444 thanks for the report. Is this consistent or sporadic? I'd like to try recreating this with the emulator if you can give me a specific device type.

**Comment by ber4444** [comment]
It's rare 
Noticed on Motorola, e.g. Edge Plus 5G UW (2022)

**Comment by ber4444** [comment]
Not seeing this any more
